// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvfFNl0PYO2m5cPEpBw6H4aELvueCwGLA',
    appId: '1:845609608653:web:3c48a7e31b5ab1527f9084',
    messagingSenderId: '845609608653',
    projectId: 'smsecure',
    authDomain: 'sm-9ca41.firebaseapp.com',
    storageBucket: 'smsecure.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSrI5tQ1bI2KkYH_TZgow1COnM-vQByI',
    appId: '1:845609608653:android:14baebb2fbe6efe57f9084',
    messagingSenderId: '845609608653',
    projectId: 'smsecure',
    storageBucket: 'smsecure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzX222ScA_ROceVvBfKx1sSOMdGut7O0',
    appId: '1:845609608653:ios:d52c68898b6fefbd7f9084',
    messagingSenderId: '845609608653',
    projectId: 'smsecure',
    storageBucket: 'smsecure.appspot.com',
    iosBundleId: 'com.smsecure.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzX222ScA_ROceVvBfKx1sSOMdGut7O0',
    appId: '1:845609608653:ios:d52c68898b6fefbd7f9084',
    messagingSenderId: '845609608653',
    projectId: 'smsecure',
    storageBucket: 'smsecure.appspot.com',
    iosBundleId: 'com.smsecure.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvfFNl0PYO2m5cPEpBw6H4aELvueCwGLA',
    appId: '1:845609608653:web:06227360046b538d7f9084',
    messagingSenderId: '845609608653',
    projectId: 'smsecure',
    authDomain: 'sm-9ca41.firebaseapp.com',
    storageBucket: 'smsecure.appspot.com',
  );

}